<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ вакансий из HeadHunter

In [1]:
import pandas as pd
import psycopg2

In [2]:
import warnings
warnings.filterwarnings('ignore', message='pandas only supports SQLAlchemy')

In [3]:
import dotenv
import os
DBNAME = os.getenv('DBNAME')
USER = os.getenv('USER')
HOST = os.getenv('HOST')
PASSWORD = os.getenv('PASSWORD')
PORT = os.getenv('PORT')

# Юнит 3. Предварительный анализ данных

1. Напишите запрос, который посчитает количество вакансий в нашей базе (вакансии находятся в таблице vacancies).

In [4]:
def connect():
    connection = psycopg2.connect(
    dbname=DBNAME,
    user=USER,
    host=HOST,
    password=PASSWORD,
    port=PORT
)
    return connection

def show_df(query):
    con = connect()
    df = pd.read_sql_query(query, con)
    con.close()
    display(df)

In [5]:
# текст запроса
query_3_1 = f'''
    SELECT *
    FROM vacancies

'''

In [6]:
show_df(query_3_1)

,id,name,key_skills,schedule,experience,employment,salary_from,salary_to,area_id,employer_id
0,55312386,Компьютерный Мастер,Пользователь ПК\tРабота в команде\tРемонт ноут...,Полный день,Нет опыта,Полная занятость,64000.0,NaN,1516,5724811
1,55843014,Системный администратор,Средства криптографической защиты информации\t...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,130,4903713
2,54525964,Lead Java Developer to Poland,Spring Framework\tSQL\tHibernate ORM\tJava\tGit,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,160,69961
3,54525965,Lead Java Developer to Poland,Spring Framework\tSQL\tHibernate ORM\tJava\tGit,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,159,69961
4,55354053,Специалист службы поддержки с техническими зна...,None,Удаленная работа,Нет опыта,Частичная занятость,15000.0,NaN,1955,1740
...,...,...,...,...,...,...,...,...,...,...
49192,55589514,Специалист по информационным технологиям,Электронный документооборот\t1С: Предприятие 8...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,66,5109332
49193,55029668,Руководитель процессного офиса,Оптимизация бизнес-процессов\tСтратегическое м...,Полный день,От 3 до 6 лет,Полная занятость,NaN,NaN,26,51333
49194,66172263,Начальник сервисной службы,Организаторские навыки\tУправление персоналом\...,Полный день,От 1 года до 3 лет,Полная занятость,60000.0,NaN,1930,4094700
49195,66180086,Senior IOS разработчик,Swift\tRealm\tiOS\tАнглийский язык\tMVP\tMVVM\...,Полный день,От 1 года до 3 лет,Полная занятость,146456.0,244094.0,160,4469939
49196,55547842,DataOps Engineer,None,Удаленная работа,От 3 до 6 лет,Полная занятость,NaN,NaN,160,4978627

2. Напишите запрос, который посчитает количество работодателей (таблица employers).

In [7]:
query_3_2 = f'''
    SELECT *
    FROM employers

'''

In [8]:
show_df(query_3_2)

            id                                               name  area
0         2393                   Программный Продукт, ИТ-компания     1
1        72977                                          БАРС Груп    88
2         3155  Бест, Торгово-производственная компания, Екате...     3
3          675                                   КОРУС Консалтинг     2
4      1840010  филиал ФКУ Налог-Сервис ФНС России в Республик...    88
...        ...                                                ...   ...
23496  1441774                                              МарКо    88
23497  4718575                                      MKomov Studio    73
23498  3702770                                  АКИБ Ипотека-банк  2759
23499  5636092                                        ГИМ-КЛИНИКА    99
23500  2064382                                             Рыббла   104

[23501 rows x 3 columns]

3. Посчитате с помощью запроса количество регионов (таблица areas).

In [9]:
query_3_3 = f'''
    SELECT *
    FROM areas
'''

In [10]:
show_df(query_3_3)

        id              name
0     2758           Тбилиси
1        8            Майкоп
2     1180          Нерюнгри
3     1240       Новокузнецк
4        2   Санкт-Петербург
...    ...               ...
1357  5043  Звёздный Городок
1358  3934       Воротынск\n
1359  4825             Чемал
1360  3708         Усть-Нера
1361  2432         Каневская

[1362 rows x 2 columns]

4. Посчитате с помощью запроса количество сфер деятельности в базе (таблица industries).

In [11]:
query_3_4 = f'''
    SELECT *
    FROM industries
'''

In [12]:
show_df(query_3_4)

          id                                               name
0      7.540                Разработка программного обеспечения
1      7.539  Системная интеграция,  автоматизации технологи...
2     27.550              Безалкогольные напитки (производство)
3     27.551  Безалкогольные напитки (продвижение, оптовая т...
4     13.664             Управление и эксплуатация недвижимости
..       ...                                                ...
289   37.626             Ассоциация в сфере культуры, искусства
290   42.603                              Табак  (производство)
291   29.532                           Рыболовство, рыбоводство
292   37.627                      Благотворительная организация
293  388.505  Оборудование для деревообработки, заготовки ле...

[294 rows x 2 columns]

Глядя на количество данных мы можем увидеть, что количество вакансий почти в два раза больше, чем количество резюме

***

# Юнит 4. Детальный анализ вакансий

1. Напишите запрос, который позволит узнать, сколько (cnt) вакансий в каждом регионе (area).
Отсортируйте по количеству вакансий в порядке убывания.

In [13]:
query_4_1 = f'''
    SELECT
        a.name area,
        COUNT(v.id)
    FROM 
        areas a
    LEFT JOIN vacancies v ON a.id = v.area_id
    GROUP BY a.name
    ORDER BY 2 DESC
'''

In [14]:
show_df(query_4_1)

                                   area  count
0                                Москва   5333
1                       Санкт-Петербург   2851
2                                 Минск   2112
3                           Новосибирск   2006
4                                Алматы   1892
...                                 ...    ...
1357                         Багаевская      0
1358                         Пролетарск      0
1359                       Седельниково      0
1360                             Инской      0
1361  Белоярский (Свердловская область)      0

[1362 rows x 2 columns]

2. Напишите запрос, чтобы определить у какого количества вакансий заполнено хотя бы одно из двух полей с зарплатой.

In [15]:
query_4_2 = f'''
    SELECT
        COUNT(v.id) cnt 
    FROM 
        vacancies v
    WHERE v.salary_from IS NOT NULL OR v.salary_to IS NOT NULL
    
'''

In [16]:
show_df(query_4_2)

     cnt
0  24073

3. Найдите средние значения для нижней и верхней границы зарплатной вилки. Округлите значения до целого.

In [17]:
query_4_3 = f'''
    SELECT
        ROUND(AVG(salary_from)) avg_from,
        ROUND(AVG(salary_to)) avg_to
    FROM 
        vacancies 
    
'''

In [18]:
show_df(query_4_3)

   avg_from    avg_to
0   71065.0  110537.0

4. Напишите запрос, который выведет количество вакансий для каждого сочетания типа рабочего графика (schedule) и типа трудоустройства (employment), используемого в вакансиях. Результат отсортируйте по убыванию количества.

In [19]:
query_4_4 = f'''
    SELECT
        v.schedule shed,
        v.employment emp,
        COUNT(v.id)
    FROM 
        vacancies v
    GROUP BY v.schedule, v.employment
    ORDER BY 3 DESC
    
'''

In [20]:
show_df(query_4_4)

                shed                  emp  count
0        Полный день     Полная занятость  35367
1   Удаленная работа     Полная занятость   7802
2      Гибкий график     Полная занятость   1593
3   Удаленная работа  Частичная занятость   1312
4     Сменный график     Полная занятость    940
5        Полный день           Стажировка    569
6     Вахтовый метод     Полная занятость    367
7        Полный день  Частичная занятость    347
8      Гибкий график  Частичная занятость    312
9        Полный день     Проектная работа    141
10  Удаленная работа     Проектная работа    133
11     Гибкий график           Стажировка    116
12    Сменный график  Частичная занятость    101
13  Удаленная работа           Стажировка     64
14     Гибкий график     Проектная работа     18
15    Сменный график           Стажировка     12
16    Вахтовый метод     Проектная работа      2
17    Сменный график     Проектная работа      1

5. Напишите запрос, выводящий значения поля Требуемый опыт работы (experience) в порядке возрастания количества вакансий, в которых указан данный вариант опыта.

In [21]:
query_4_5 = f'''
    SELECT
        v.experience,
        COUNT(v.id)
    FROM 
        vacancies v
    GROUP BY v.experience
    ORDER BY 2
    
'''

In [22]:
show_df(query_4_5)

           experience  count
0         Более 6 лет   1337
1           Нет опыта   7197
2       От 3 до 6 лет  14511
3  От 1 года до 3 лет  26152

Вывод:
Мы можем увидеть, что предоставленные вакансии не ограничиваются РФ, множество вакансий также предоставляются в странах СНГ.
Наибольшее количество вакансий ожидаемо находятся в городах миллионниках и столицах.

Примерно в половине вакансий не указаны зарплаты.
Средние зарплаты вариируются от 71 до 110 тысяч.

Большинство вакансий предполагают полный день и полную занятость, что не удивительно. 

А вот что удивительно:
вакансий, где опыт не требуется почти в 7 раз больше, чем вакансий, где требуется опыт более 6-ти лет. Но большая часть вакансий предполагает минимальный опыт от 1 до 6 лет.

***

# Юнит 5. Анализ работодателей

1. Напишите запрос, который позволит узнать, какие работодатели находятся на первом и пятом месте по количеству вакансий.

In [23]:
query_5_1 = f'''
    SELECT
        e.name emp,
        COUNT(v.id)
    FROM 
        employers e
    LEFT JOIN vacancies v ON e.id = v.employer_id
    GROUP BY e.name
    ORDER BY 2 DESC
'''

In [24]:
show_df(query_5_1)

                                      emp  count
0                                  Яндекс   1933
1                              Ростелеком    491
2                                Тинькофф    444
3                                    СБЕР    428
4                           Газпром нефть    331
...                                   ...    ...
23170      Капитал Лайф Страхование Жизни      0
23171                            AGASTONE      0
23172                       Независимость      0
23173  Верховный Суд Республики Татарстан      0
23174                            Трекмарк      0

[23175 rows x 2 columns]

2. Напишите запрос, который для каждого региона выведет количество работодателей и вакансий в нём.
Среди регионов, в которых нет вакансий, найдите тот, в котором наибольшее количество работодателей.

In [25]:
query_5_2 = f'''
    SELECT
        a.name area,
        COUNT(e.name) cnt_emp,
        COUNT(v.id)
    FROM 
        areas a
    LEFT JOIN employers e ON e.area = a.id
    LEFT JOIN vacancies v ON a.id = v.area_id   
    GROUP BY a.name
    ORDER BY 3 NULLS FIRST, 2 DESC
'''

In [26]:
show_df(query_5_2)

                    area   cnt_emp     count
0                 Россия       410         0
1              Казахстан       207         0
2     Московская область        75         0
3     Краснодарский край        19         0
4     Ростовская область        18         0
...                  ...       ...       ...
1357         Новосибирск   1149438   1149438
1358              Алматы   1364132   1364132
1359               Минск   2354880   2354880
1360     Санкт-Петербург   6320667   6320667
1361              Москва  31272712  31272712

[1362 rows x 3 columns]

3. Для каждого работодателя посчитайте количество регионов, в которых он публикует свои вакансии. Отсортируйте результат по убыванию количества.

In [27]:
query_5_3 = f'''
    SELECT
        e.name emp,
        COUNT(DISTINCT v.area_id) cnt_area
    FROM 
        employers e
    LEFT JOIN vacancies v ON v.employer_id = e.id 
    GROUP BY e.id, e.name
    ORDER BY 2 DESC
'''

In [29]:
show_df(query_5_3)

                          emp  cnt_area
0                      Яндекс       181
1                  Ростелеком       152
2                  Спецремонт       116
3      Поляков Денис Иванович        88
4                   ООО ЕФИН         71
...                       ...       ...
23496              Но Смокинг         0
23497        МАСТЕРСКАЯ CREED         0
23498           Dzing Finance         0
23499                    КОРС         0
23500             Наука-Связь         0

[23501 rows x 2 columns]

4. Напишите запрос для подсчёта количества работодателей, у которых не указана сфера деятельности.

In [30]:
query_5_4 = f'''
    SELECT
        COUNT(e.name) cnt_emp
    FROM 
        employers e
    LEFT JOIN employers_industries ei ON e.id = ei.employer_id
        WHERE ei.employer_id IS NULL
    '''

In [31]:
show_df(query_5_4)

   cnt_emp
0     8419

5. Напишите запрос, чтобы узнать название компании, находящейся на третьем месте в алфавитном списке (по названию) компаний, у которых указано четыре сферы деятельности.

In [32]:
query_5_5 = f'''
    SELECT
        e.name emp,
        COUNT(ei.employer_id) len_sph
    FROM 
        employers e
    LEFT JOIN employers_industries ei ON e.id = ei.employer_id
    GROUP BY e.name
    HAVING COUNT(ei.employer_id) = 4
    ORDER BY 1
    OFFSET 2
    LIMIT 1
    '''

In [33]:
show_df(query_5_5)

    emp  len_sph
0  2ГИС        4

6. С помощью запроса выясните, у какого количества работодателей в качестве сферы деятельности указана Разработка программного обеспечения.

In [34]:
query_5_6 = f'''
    SELECT
        COUNT(e.employer_id) cnt_emp
    FROM 
        employers_industries e
    LEFT JOIN industries i ON e.industry_id = i.id
    WHERE i.name = 'Разработка программного обеспечения'
    
    '''

In [35]:
show_df(query_5_6)

   cnt_emp
0     3553

7. Для компании «Яндекс» выведите список регионов-миллионников, в которых представлены вакансии компании, вместе с количеством вакансий в этих регионах. Также добавьте строку Total с общим количеством вакансий компании. Результат отсортируйте по возрастанию количества.

Список городов-милионников надо взять [отсюда](https://ru.wikipedia.org/wiki/%D0%93%D0%BE%D1%80%D0%BE%D0%B4%D0%B0-%D0%BC%D0%B8%D0%BB%D0%BB%D0%B8%D0%BE%D0%BD%D0%B5%D1%80%D1%8B_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8). 

Если возникнут трудности с этим задание посмотрите материалы модуля  PYTHON-17. Как получать данные из веб-источников и API.

In [36]:
query_5_7 = f'''
    SELECT
        a.name AS name,
        COUNT(v.id) AS cnt
    FROM 
        areas AS a
    LEFT JOIN vacancies AS v ON a.id = v.area_id
    LEFT JOIN employers AS e ON e.id = v.employer_id
    WHERE a.name IN (
        'Москва', 'Санкт-Петербург', 'Новосибирск',
        'Екатеринбург', 'Казань', 'Красноярск',
        'Нижний Новгород', 'Челябинск', 'Уфа',
        'Самара', 'Краснодар', 'Ростов-на-Дону',
        'Омск', 'Воронеж', 'Пермь', 'Волгоград'
    )
    AND e.name = 'Яндекс'
    GROUP BY a.name
    UNION ALL
    SELECT
        'Total' AS name,
        COUNT(v.id) AS cnt
    FROM 
        areas AS a
    LEFT JOIN vacancies AS v ON a.id = v.area_id
    LEFT JOIN employers AS e ON e.id = v.employer_id
    WHERE a.name IN (
        'Москва', 'Санкт-Петербург', 'Новосибирск',
        'Екатеринбург', 'Казань', 'Красноярск',
        'Нижний Новгород', 'Челябинск', 'Уфа',
        'Самара', 'Краснодар', 'Ростов-на-Дону',
        'Омск', 'Воронеж', 'Пермь', 'Волгоград'
    )
    AND e.name = 'Яндекс'
    ORDER BY 2

'''

In [37]:
show_df(query_5_7)

               name  cnt
0              Омск   21
1         Челябинск   22
2        Красноярск   23
3         Волгоград   24
4             Пермь   25
5            Казань   25
6    Ростов-на-Дону   25
7               Уфа   26
8            Самара   26
9         Краснодар   30
10          Воронеж   32
11      Новосибирск   35
12  Нижний Новгород   36
13     Екатеринбург   39
14  Санкт-Петербург   42
15           Москва   54
16            Total  485

***

Вывод:
На первом месте с большим отрывом по количеству вакансий выигрывает яндекс (больше чем у следующих 4 мест вместе взятых)

Регионы для работадателей и для вакансий - это разные вещи. Для работадателей это страны/области, а для вакансий, как правило, города.

У трети работадателей не указана сфера деятельности.

# Юнит 6. Предметный анализ

1. Сколько вакансий имеет отношение к данным?

Считаем, что вакансия имеет отношение к данным, если в её названии содержатся слова 'data' или 'данн'.

*Подсказка: Обратите внимание, что названия вакансий могут быть написаны в любом регистре.*

In [38]:
query_6_1 = f'''
    SELECT
        COUNT(v.id) cnt_vac
    FROM 
        vacancies v
    WHERE LOWER(v.name) LIKE '%data%' OR LOWER(v.name) LIKE '%данн%'    
    '''

In [39]:
show_df(query_6_1)

   cnt_vac
0     1771

2. Сколько есть подходящих вакансий для начинающего дата-сайентиста? 
Будем считать вакансиями для дата-сайентистов такие, в названии которых есть хотя бы одно из следующих сочетаний:
* 'data scientist'
* 'data science'
* 'исследователь данных'
* 'ML' (здесь не нужно брать вакансии по HTML)
* 'machine learning'
* 'машинн%обучен%'

** В следующих заданиях мы продолжим работать с вакансиями по этому условию.*

Считаем вакансиями для специалистов уровня Junior следующие:
* в названии есть слово 'junior' *или*
* требуемый опыт — Нет опыта *или*
* тип трудоустройства — Стажировка.

In [40]:
query_6_2 = f'''
    SELECT
        COUNT(v.id) cnt_vac
    FROM 
        vacancies v
    WHERE LOWER(v.name) ~ 'data scientist|data science|исследователь данных|ml|machine learning|машин.*обучен'
        AND LOWER(v.name) NOT LIKE '%html%'
        AND (
            LOWER(v.name) LIKE '%junior%' 
            OR LOWER(v.experience) = 'нет опыта'
            OR LOWER(v.employment) = 'стажировка')

    '''

In [41]:
show_df(query_6_2)

   cnt_vac
0       51

In [58]:
print(51/49197*100)

0.1036648576132691

3. Сколько есть вакансий для DS, в которых в качестве ключевого навыка указан SQL или postgres?

** Критерии для отнесения вакансии к DS указаны в предыдущем задании.*

In [42]:
query_6_3 = f'''       
            SELECT count(id)
            FROM vacancies
            WHERE
            ( name ILIKE '%data scientist%' OR 
              name ILIKE '%data science%' OR 
              name ILIKE '%исследователь данных%' OR 
              name ILIKE '%machine learning%' OR 
              name ILIKE '%машинн%обучен%' OR 
              name LIKE '%ML%' AND name NOT ILIKE '%HTML%' )
            AND
            ( key_skills ILIKE '%SQL%' OR key_skills ILIKE '%postgres%' )
            '''

In [43]:
show_df(query_6_3)

   count
0    201

4. Проверьте, насколько популярен Python в требованиях работодателей к DS.Для этого вычислите количество вакансий, в которых в качестве ключевого навыка указан Python.

** Это можно сделать помощью запроса, аналогичного предыдущему.*

In [44]:
query_6_4 = f'''       
            SELECT count(id)
            FROM vacancies
            WHERE
            ( name ILIKE '%data scientist%' OR 
              name ILIKE '%data science%' OR 
              name ILIKE '%исследователь данных%' OR 
              name ILIKE '%machine learning%' OR 
              name ILIKE '%машинн%обучен%' OR 
              name LIKE '%ML%' AND name NOT ILIKE '%HTML%' )
            AND LOWER(key_skills) ILIKE '%python%' 
            '''

In [45]:
show_df(query_6_4)

   count
0    351

5. Сколько ключевых навыков в среднем указывают в вакансиях для DS?
Ответ округлите до двух знаков после точки-разделителя.

In [46]:
query_6_5 = f'''       
            SELECT 
                ROUND(AVG(
            COALESCE(
                LENGTH(key_skills) - LENGTH(REPLACE(key_skills, '\t', '')) + 1,
                0
            )
        ), 2) AS avg_skills_count
            FROM vacancies
            WHERE
            ( name ILIKE '%data scientist%' OR 
              name ILIKE '%data science%' OR 
              name ILIKE '%исследователь данных%' OR 
              name ILIKE '%machine learning%' OR 
              name ILIKE '%машинн%обучен%' OR 
              name LIKE '%ML%' AND name NOT ILIKE '%HTML%' )
            AND key_skills IS NOT NULL
            '''

In [47]:
show_df(query_6_5)

   avg_skills_count
0              6.41

6. Напишите запрос, позволяющий вычислить, какую зарплату для DS в **среднем** указывают для каждого типа требуемого опыта (уникальное значение из поля *experience*). 

При решении задачи примите во внимание следующее:
1. Рассматриваем только вакансии, у которых заполнено хотя бы одно из двух полей с зарплатой.
2. Если заполнены оба поля с зарплатой, то считаем зарплату по каждой вакансии как сумму двух полей, делённую на 2. Если заполнено только одно из полей, то его и считаем зарплатой по вакансии.
3. Если в расчётах участвует null, в результате он тоже даст null (посмотрите, что возвращает запрос select 1 + null). Чтобы избежать этой ситуацию, мы воспользуемся функцией [coalesce](https://postgrespro.ru/docs/postgresql/9.5/functions-conditional#functions-coalesce-nvl-ifnull), которая заменит null на значение, которое мы передадим. Например, посмотрите, что возвращает запрос `select 1 + coalesce(null, 0)`

Выясните, на какую зарплату в среднем может рассчитывать дата-сайентист с опытом работы от 3 до 6 лет. Результат округлите до целого числа.

In [56]:
query_6_6_1 = f'''       
                SELECT 
    experience,
    ROUND(AVG(COALESCE((salary_from + salary_to) / 2, salary_from, salary_to)), 0) AS avg_salary
FROM vacancies
WHERE (
    name ILIKE '%data scientist%'
    OR name ILIKE '%data science%'
    OR name ILIKE '%исследователь данных%'
    OR (name LIKE '%ML%' AND name NOT ILIKE '%html%')
    OR name ILIKE '%machine learning%'
    OR (name ILIKE '%машинн%обучен%' AND key_skills IS NOT NULL)
)
AND (salary_from IS NOT NULL OR salary_to IS NOT NULL)
GROUP BY experience
ORDER BY experience
                        '''

In [57]:
show_df(query_6_6_1)

           experience  avg_salary
0           Нет опыта     74643.0
1  От 1 года до 3 лет    145236.0
2       От 3 до 6 лет    243115.0

Проведенный предметный анализ показывает, что вакансий по data scince и ML для джунов очень мало: всего 0.10%.

Средняя зарплата для человека без опыта в данной сфере (к тому года) - ~75 000, но черезз 3-5 лет можно рассчитывать на зарплату в три раза больше - ~250 000, что является хорошей разницей за такое количество лет опыта.


В среднем соискателю нужно обладать 6-7 навыками для работы в данной профессии

***

# Общий вывод по проекту

In [61]:
query_7_1 = f'''
    SELECT
        COUNT(v.id) cnt_vac
    FROM 
        vacancies v
    WHERE LOWER(v.name) ~ 'data scientist|data science|исследователь данных|ml|machine learning|машин.*обучен'
        AND LOWER(v.name) NOT LIKE '%html%'

    '''

In [62]:
show_df(query_7_1) #всего вакансий ML и DS

   cnt_vac
0      536

In [63]:
print(201/536*100) # процент вакансий, в котором фигурирует SQL и postgres

37.5

In [64]:
print(351/536*100) # процент вакансий, в котором фигурирует python

65.48507462686567

Более чем в 65% вакансий требуется знание python, а вот a sql или postgres только в 38, что очень странно, на мой взгляд, так как это фундаментальные знания для работы DS

In [67]:
query_7_2 = f'''       
                SELECT 
    experience,
    COUNT(*)
FROM vacancies
WHERE (
    name ILIKE '%data scientist%'
    OR name ILIKE '%data science%'
    OR name ILIKE '%исследователь данных%'
    OR (name LIKE '%ML%' AND name NOT ILIKE '%html%')
    OR name ILIKE '%machine learning%'
    OR (name ILIKE '%машинн%обучен%')
)GROUP BY experience
ORDER BY experience
                        '''

In [68]:
show_df(query_7_2)

           experience  count
0         Более 6 лет     34
1           Нет опыта     28
2  От 1 года до 3 лет    223
3       От 3 до 6 лет    195

Если мы посмотрим на задание 6.1, где мы определяли среднюю зарплату в зависимости от опыта работы, то увидим, что там не было группы с опытом Более 6 лет, значит для такой группы по каким-то причинам не пишут ЗП. 

Основная часть вакансий по DS и ML ищут человека с опытом от 1 до 6 лет, а вот без опыта предлагается очень мало позиций, даже меньше, чем предполагалось ранее (так как по ключевым словам мы нашли 51 вакансию, а не 28, как здесь)


- 49 197 вакансий, 23 501 работодатель, 1 362 региона, 294 сферы деятельности
- Больше всего вакансий в Москве (5 333), Санкт-Петербурге (2 851) и Минске (2 112)
- У ~49% вакансий указана хотя бы одна граница зарплаты; средняя вилка: 71 065 – 110 537 ₽
- Лидер по числу вакансий — Яндекс (1 933)
- Вакансий, связанных с данными (`data` / `данн` в названии): 1 771
- Вакансий DS/ML: 536; для junior-специалистов — всего 51 (~0,1% от всех вакансий)
- В DS-вакансиях Python встречается в 65% случаев, SQL/PostgreSQL — в 38%
- Среднее число ключевых навыков в DS-вакансиях: 6,4
- Средняя зарплата DS по опыту: без опыта — ~75 тыс., 1–3 года — ~145 тыс., 3–6 лет — ~243 тыс.₽